# Generated by Django 6.0.1 on 2026-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_seed_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='banner_image_one',
            field=models.FileField(blank=True, help_text='Recommended size: 1170x457', upload_to='projects/banners/'),
        ),
        migrations.AddField(
            model_name='project',
            name='banner_image_two',
            field=models.FileField(blank=True, help_text='Recommended size: 1170x457', upload_to='projects/banners/'),
        ),
        migrations.AddField(
            model_name='project',
            name='unique_vision_goal_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='unique_vision_goal_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='unique_vision_goal_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='unique_vision_goal_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='project_images', to='UI.projectcategory'),
        ),
    ]
