# Generated by Django 6.0.1 on 2026-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_project_banner_image_one_project_banner_image_two_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FileField(help_text='Aspect ratio 2:1. Recommended: 1170x585 (fits project-details layout) or 1920x960 for higher quality.', upload_to='projects/main/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short Description 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short Description 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short Description 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Short Description 4'),
        ),
    ]
