# Generated by Django 6.0.1 on 2026-02-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_alter_project_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.RemoveField(
            model_name='project',
            name='subdetails',
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_1',
            field=models.TextField(blank=True, verbose_name='Short Description 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_2',
            field=models.TextField(blank=True, verbose_name='Short Description 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_3',
            field=models.TextField(blank=True, verbose_name='Short Description 3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_4',
            field=models.TextField(blank=True, verbose_name='Short Description 4'),
        ),
    ]
