# Generated by Django 6.0.1 on 2026-02-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_remove_project_details_remove_project_subdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='listing_image',
            field=models.FileField(blank=True, help_text='Used on project listing cards. Recommended portrait image around 640x960.', upload_to='projects/listing/'),
        ),
    ]
