# Generated by Django 6.0.1 on 2026-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0006_project_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_1',
            field=models.TextField(blank=True, verbose_name='The Vision'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_2',
            field=models.TextField(blank=True, verbose_name='The BrieF'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_3',
            field=models.TextField(blank=True, verbose_name='The Transformation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_vision_goal_4',
            field=models.TextField(blank=True, verbose_name='The Outcome'),
        ),
    ]
