# Generated by Django 6.0.1 on 2026-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0010_projectimage_single_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_map_iframe',
            field=models.TextField(blank=True, help_text='Paste full Google Maps iframe embed code.'),
        ),
    ]
