# Generated by Django 6.0.1 on 2026-02-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0012_project_latitude_project_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image_one',
            field=models.FileField(blank=True, help_text='Auto-cropped to 1170x585 (2:1).', upload_to='projects/banners/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='banner_image_two',
            field=models.FileField(blank=True, help_text='Auto-cropped to 1170x585 (2:1).', upload_to='projects/banners/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='listing_image',
            field=models.FileField(blank=True, help_text='Auto-cropped to 570x400 (57:40). Upload any high-quality image.', upload_to='projects/listing/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.FileField(help_text='Auto-cropped to 1170x585 (2:1) for project-details hero.', upload_to='projects/main/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.FileField(help_text='Auto-cropped to 1170x780 (3:2) for consistent gallery layout.', upload_to='projects/gallery/'),
        ),
    ]
