# Generated by Django 6.0.1 on 2026-02-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0013_alter_project_banner_image_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='location_postcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
