# Generated by Django 6.0.1 on 2026-02-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0014_project_location_city_project_location_postcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X (Twitter) URL')),
                ('youtube_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Social Links',
                'verbose_name_plural': 'Site Social Links',
            },
        ),
    ]
