# Generated by Django 6.0.1 on 2026-02-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0015_sitesociallinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesociallinks',
            name='x_url',
        ),
        migrations.RemoveField(
            model_name='sitesociallinks',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='sitesociallinks',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
