# Generated by Django 6.0.1 on 2026-03-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0016_remove_sitesociallinks_x_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField()),
                ('photo', models.FileField(blank=True, upload_to='testimonials/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
