# Generated by Django 6.0.1 on 2026-03-01 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0017_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True)),
                ('is_used', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
